Repository EdenEast/nightfox.nvim, pull requests merged in 2022-04, with the labels that each got.

#114 Add bufferline support
  doc/nightfox.txt
  lua/nightfox/config.lua
  lua/nightfox/group/modules/bufferline.lua
  lua/nightfox/precompiled/dawnfox_compiled.lua
  lua/nightfox/precompiled/dayfox_compiled.lua
  lua/nightfox/precompiled/duskfox_compiled.lua
  lua/nightfox/precompiled/nightfox_compiled.lua
  lua/nightfox/precompiled/nordfox_compiled.lua
  readme.md
  usage.md
Labels: enhancement, module

#121 fix(palette): Increase contrast for `duskfox` folds
  extra/duskfox/nightfox_konsole.colorscheme
  extra/duskfox/nightfox_tmux.tmux
  lua/nightfox/group/editor.lua
  lua/nightfox/palette/duskfox.lua
  lua/nightfox/precompiled/dawnfox_compiled.lua
  lua/nightfox/precompiled/dayfox_compiled.lua
  lua/nightfox/precompiled/duskfox_compiled.lua
  lua/nightfox/precompiled/nightfox_compiled.lua
  lua/nightfox/precompiled/nordfox_compiled.lua
  lua/nightfox/precompiled/terafox_compiled.lua
Labels: bug

#122 feat(module): Add nvim-notify
  doc/nightfox.txt
  lua/nightfox/config.lua
  lua/nightfox/group/modules/notify.lua
  lua/nightfox/precompiled/dawnfox_compiled.lua
  lua/nightfox/precompiled/dayfox_compiled.lua
  lua/nightfox/precompiled/duskfox_compiled.lua
  lua/nightfox/precompiled/nightfox_compiled.lua
  lua/nightfox/precompiled/nordfox_compiled.lua
  lua/nightfox/precompiled/terafox_compiled.lua
  readme.md
  usage.md
Labels: enhancement, module

#129 feat(config): Add missing syntax styles
  doc/nightfox.txt
  lua/nightfox/config.lua
  lua/nightfox/group/modules/treesitter.lua
  lua/nightfox/group/syntax.lua
  readme.md
  usage.md
Labels: enhancement

#127 Feat/interactive
  doc/nightfox.txt
  lua/nightfox/config.lua
  lua/nightfox/interactive.lua
  lua/nightfox/lib/collect.lua
  lua/nightfox/override.lua
  plugin/nightfox.vim
  readme.md
  usage.md
Labels: enhancement

#130 chore(extra): Add comment for optional cursor none
  extra/dawnfox/nightfox_kitty.conf
  extra/dayfox/nightfox_kitty.conf
  extra/duskfox/nightfox_kitty.conf
  extra/nightfox/nightfox_kitty.conf
  extra/nordfox/nightfox_kitty.conf
  extra/terafox/nightfox_kitty.conf
  lua/nightfox/extra/kitty.lua
Labels: extras

#132 Support `nvim-0.7`'s `nvim_set_hl` api
  flake.nix
  lua/nightfox/lib/compile.lua
  lua/nightfox/lib/highlight.lua
  lua/nightfox/main.lua
  lua/nightfox/precompiled/nvim/dawnfox_compiled.lua
  lua/nightfox/precompiled/nvim/dayfox_compiled.lua
  lua/nightfox/precompiled/nvim/duskfox_compiled.lua
  lua/nightfox/precompiled/nvim/nightfox_compiled.lua
  lua/nightfox/precompiled/nvim/nordfox_compiled.lua
  lua/nightfox/precompiled/nvim/terafox_compiled.lua
  lua/nightfox/precompiled/viml/dawnfox_compiled.lua
  lua/nightfox/precompiled/viml/dayfox_compiled.lua
  lua/nightfox/precompiled/viml/duskfox_compiled.lua
  lua/nightfox/precompiled/viml/nightfox_compiled.lua
  lua/nightfox/precompiled/viml/nordfox_compiled.lua
  lua/nightfox/precompiled/viml/terafox_compiled.lua
  lua/nightfox/util/init.lua
  misc/benchmarks/01-nvim-viml-compiled.lua
  misc/precompile.lua
Labels: enhancement, compiler

#134 fix(compile): Guard missing opts
  lua/nightfox/lib/compile.lua
Labels: bug, compiler

#137 Change inverse to reverse
  lua/nightfox/group/editor.lua
Labels: bug, compiler

#138 `all` override for `palette` and `spec`
  lua/nightfox/palette.lua
  lua/nightfox/spec.lua
  lua/nightfox/util/template.lua
  readme.md
Labels: enhancement

#140 fix(module): Remove reference to `bufferline`
  doc/nightfox.txt
  lua/nightfox/config.lua
  lua/nightfox/group/modules/bufferline.lua
  lua/nightfox/precompiled/nvim/dawnfox_compiled.lua
  lua/nightfox/precompiled/nvim/dayfox_compiled.lua
  lua/nightfox/precompiled/nvim/duskfox_compiled.lua
  lua/nightfox/precompiled/nvim/nightfox_compiled.lua
  lua/nightfox/precompiled/nvim/nordfox_compiled.lua
  lua/nightfox/precompiled/nvim/terafox_compiled.lua
  lua/nightfox/precompiled/viml/dawnfox_compiled.lua
  lua/nightfox/precompiled/viml/dayfox_compiled.lua
  lua/nightfox/precompiled/viml/duskfox_compiled.lua
  lua/nightfox/precompiled/viml/nightfox_compiled.lua
  lua/nightfox/precompiled/viml/nordfox_compiled.lua
  lua/nightfox/precompiled/viml/terafox_compiled.lua
  readme.md
  usage.md
Labels: bug, module

#141 fix(lib): Hackly workaround for neovim core bug
  lua/nightfox/lib/compile.lua
  lua/nightfox/lib/highlight.lua
  lua/nightfox/main.lua
  lua/nightfox/precompiled/nvim/dawnfox_compiled.lua
  lua/nightfox/precompiled/nvim/dayfox_compiled.lua
  lua/nightfox/precompiled/nvim/duskfox_compiled.lua
  lua/nightfox/precompiled/nvim/nightfox_compiled.lua
  lua/nightfox/precompiled/nvim/nordfox_compiled.lua
  lua/nightfox/precompiled/nvim/terafox_compiled.lua
Labels: bug, compiler

#143 feat: add CurSearch highlight group
  lua/nightfox/group/editor.lua
  lua/nightfox/precompiled/nvim/dawnfox_compiled.lua
  lua/nightfox/precompiled/nvim/dayfox_compiled.lua
  lua/nightfox/precompiled/nvim/duskfox_compiled.lua
  lua/nightfox/precompiled/nvim/nightfox_compiled.lua
  lua/nightfox/precompiled/nvim/nordfox_compiled.lua
  lua/nightfox/precompiled/nvim/terafox_compiled.lua
  lua/nightfox/precompiled/viml/dawnfox_compiled.lua
  lua/nightfox/precompiled/viml/dayfox_compiled.lua
  lua/nightfox/precompiled/viml/duskfox_compiled.lua
  lua/nightfox/precompiled/viml/nightfox_compiled.lua
  lua/nightfox/precompiled/viml/nordfox_compiled.lua
  lua/nightfox/precompiled/viml/terafox_compiled.lua
Labels: enhancement

#144 feat: Support lightline again
  autoload/lightline/colorscheme/dawnfox.vim
  autoload/lightline/colorscheme/dayfox.vim
  autoload/lightline/colorscheme/duskfox.vim
  autoload/lightline/colorscheme/nightfox.vim
  autoload/lightline/colorscheme/nordfox.vim
  autoload/lightline/colorscheme/terafox.vim
  lua/nightfox/lib/color.lua
  lua/nightfox/util/lightline.lua
  readme.md
Labels: enhancement
