Repository EdenEast/nightfox.nvim, pull requests merged in 2022-07, with the labels that each got.

#173 Feline and Tabby example
  minimal_init.lua
  misc/feline.lua
  misc/tabby.lua
  readme.md
Labels: documentation, enhancement

#174 Add explicit support for 'mini.nvim'
  doc/nightfox.txt
  lua/nightfox/config.lua
  lua/nightfox/group/modules/mini.lua
  lua/nightfox/precompiled/nvim/dawnfox_compiled.lua
  lua/nightfox/precompiled/nvim/dayfox_compiled.lua
  lua/nightfox/precompiled/nvim/duskfox_compiled.lua
  lua/nightfox/precompiled/nvim/nightfox_compiled.lua
  lua/nightfox/precompiled/nvim/nordfox_compiled.lua
  lua/nightfox/precompiled/nvim/terafox_compiled.lua
  lua/nightfox/precompiled/viml/dawnfox_compiled.lua
  lua/nightfox/precompiled/viml/dayfox_compiled.lua
  lua/nightfox/precompiled/viml/duskfox_compiled.lua
  lua/nightfox/precompiled/viml/nightfox_compiled.lua
  lua/nightfox/precompiled/viml/nordfox_compiled.lua
  lua/nightfox/precompiled/viml/terafox_compiled.lua
  readme.md
  usage.md
Labels: enhancement, module

#177 docs: Document multiple setup calls
  readme.md
Labels: documentation

#182 Add logo from @keifererikson
  readme.md
Labels: documentation

#188 fix(lightline): Define correct `tabline` fields
  lua/nightfox/util/lightline.lua
Labels: bug
